// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusRoute.Infrastructure.Data;

#nullable disable

namespace NexusRoute.Infrastructure.Migrations
{
    [DbContext(typeof(NexusRouteDbContext))]
    [Migration("20260608093438_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("NexusRoute.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConvoyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("ConvoyId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsActive", "Severity");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("NexusRoute.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CurrentLatitude")
                        .HasColumnType("REAL");

                    b.Property<string>("CurrentLocation")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double?>("CurrentLongitude")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastTelemetryTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetCode")
                        .IsUnique();

                    b.HasIndex("LastTelemetryTime");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("NexusRoute.Domain.Entities.Checkpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("AllowedDeviationTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("ExpectedTimeFromStart")
                        .HasColumnType("TEXT");

                    b.Property<double>("GeofenceRadiusKm")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("RouteId", "SequenceNumber");

                    b.ToTable("Checkpoints");
                });

            modelBuilder.Entity("NexusRoute.Domain.Entities.Convoy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualDepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("CargoType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("CargoValueUsd")
                        .HasColumnType("REAL");

                    b.Property<string>("ConvoyCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHighPriority")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LeadAssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledDepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConvoyCode")
                        .IsUnique();

                    b.HasIndex("LeadAssetId");

                    b.HasIndex("RouteId");

                    b.HasIndex("ScheduledDepartureTime");

                    b.HasIndex("Status");

                    b.ToTable("Convoys");
                });

            modelBuilder.Entity("NexusRoute.Domain.Entities.ConvoyCheckpointLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CheckpointId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConvoyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMissed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOverdue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CheckpointId");

                    b.HasIndex("ConvoyId");

                    b.HasIndex("ConvoyId", "CheckpointId");

                    b.ToTable("ConvoyCheckpointLogs");
                });

            modelBuilder.Entity("NexusRoute.Domain.Entities.OreMovementLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CycleId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DestinationLatitude")
                        .HasColumnType("REAL");

                    b.Property<string>("DestinationLocation")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double?>("DestinationLongitude")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double?>("GradeEstimate")
                        .HasColumnType("REAL");

                    b.Property<int>("MaterialType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("SourceLatitude")
                        .HasColumnType("REAL");

                    b.Property<string>("SourceLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("SourceLongitude")
                        .HasColumnType("REAL");

                    b.Property<double>("TonnageEstimate")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("CycleId");

                    b.HasIndex("EventTime");

                    b.HasIndex("AssetId", "EventTime");

                    b.ToTable("OreMovementLogs");
                });

            modelBuilder.Entity("NexusRoute.Domain.Entities.ProductionQuota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("ActualGrade")
                        .HasColumnType("REAL");

                    b.Property<double>("ActualTonnage")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaterialType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PeriodName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TargetGrade")
                        .HasColumnType("REAL");

                    b.Property<double>("TargetTonnage")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EndDate");

                    b.HasIndex("StartDate");

                    b.HasIndex("StartDate", "EndDate");

                    b.ToTable("ProductionQuotas");
                });

            modelBuilder.Entity("NexusRoute.Domain.Entities.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<double>("EndLatitude")
                        .HasColumnType("REAL");

                    b.Property<string>("EndLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("EndLongitude")
                        .HasColumnType("REAL");

                    b.Property<double>("EstimatedDistanceKm")
                        .HasColumnType("REAL");

                    b.Property<TimeSpan>("EstimatedDuration")
                        .HasColumnType("TEXT");

                    b.Property<double>("GeofenceRadiusKm")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("StartLatitude")
                        .HasColumnType("REAL");

                    b.Property<string>("StartLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("StartLongitude")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("NexusRoute.Domain.Entities.Telemetry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Altitude")
                        .HasColumnType("REAL");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<double>("EngineTemperatureCelsius")
                        .HasColumnType("REAL");

                    b.Property<double>("FuelLevelPercentage")
                        .HasColumnType("REAL");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<double>("PayloadWeightTonnes")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("TirePressurePsi")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("AssetId", "Timestamp");

                    b.ToTable("Telemetry");
                });

            modelBuilder.Entity("NexusRoute.Domain.Entities.Alert", b =>
                {
                    b.HasOne("NexusRoute.Domain.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NexusRoute.Domain.Entities.Convoy", "Convoy")
                        .WithMany()
                        .HasForeignKey("ConvoyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Asset");

                    b.Navigation("Convoy");
                });

            modelBuilder.Entity("NexusRoute.Domain.Entities.Checkpoint", b =>
                {
                    b.HasOne("NexusRoute.Domain.Entities.Route", "Route")
                        .WithMany("Checkpoints")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("NexusRoute.Domain.Entities.Convoy", b =>
                {
                    b.HasOne("NexusRoute.Domain.Entities.Asset", "LeadAsset")
                        .WithMany()
                        .HasForeignKey("LeadAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexusRoute.Domain.Entities.Route", "Route")
                        .WithMany("Convoys")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LeadAsset");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("NexusRoute.Domain.Entities.ConvoyCheckpointLog", b =>
                {
                    b.HasOne("NexusRoute.Domain.Entities.Checkpoint", "Checkpoint")
                        .WithMany()
                        .HasForeignKey("CheckpointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexusRoute.Domain.Entities.Convoy", "Convoy")
                        .WithMany("CheckpointLogs")
                        .HasForeignKey("ConvoyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checkpoint");

                    b.Navigation("Convoy");
                });

            modelBuilder.Entity("NexusRoute.Domain.Entities.OreMovementLog", b =>
                {
                    b.HasOne("NexusRoute.Domain.Entities.Asset", "Asset")
                        .WithMany("OreMovementLogs")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("NexusRoute.Domain.Entities.Telemetry", b =>
                {
                    b.HasOne("NexusRoute.Domain.Entities.Asset", "Asset")
                        .WithMany("TelemetryRecords")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("NexusRoute.Domain.Entities.Asset", b =>
                {
                    b.Navigation("OreMovementLogs");

                    b.Navigation("TelemetryRecords");
                });

            modelBuilder.Entity("NexusRoute.Domain.Entities.Convoy", b =>
                {
                    b.Navigation("CheckpointLogs");
                });

            modelBuilder.Entity("NexusRoute.Domain.Entities.Route", b =>
                {
                    b.Navigation("Checkpoints");

                    b.Navigation("Convoys");
                });
#pragma warning restore 612, 618
        }
    }
}
